### ISSUE TITLE
Chanhe ourdated Cliqz by Ublock origin extension or by integrating and enabling "adguard dns" doh dns over https (or quad9 dns) to blocks ads and malware and crypto jacking mining

### ISSUE THREAD

**Issue by trimechee** [Alex313031/quark-player#15]
Hello, it seems that Cliqz the browser and the search engine is sadly no more developed : 

https://cliqz.com/en/magazine/farewell-from-cliqz   

 and  description of Quark player says  : "AdBlocker (provided by Cliqz)"

may be it wll be good to replace cliqz adblocker by the famous extesion adblocker "ublock origin"

https://ublockorigin.com/

 or by activating by default in Quark player the doh dns over https of adguard dns which is not an aggressive dns and it avoids false postiives and should be compatible with the majority of sites and services while blocking ads and malwares and crypto mining  , or add option to enbale quad9 dns which 

https://adguard-dns.io/en/public-dns.html

Thank you !

EDIT : boosted with artificlele intelligence which is the most powerful dns in the world to block malware according to a study by blocking 97% of threats while the second dns in the ranking of this scientific study only blocks 57% of threats!

our dream is to have quad9 dns combined with ad blocking lists but apparently some companies that fund quad9 are funded by ads.....but that said the pure android quad9 application will allow importing custom lists ....but as long as quad9 does not block ads, I think it is better to integrate in Quak Player an option to activate "adguard dns" because the comfort in a video player is to be able to enjoy videos without ads.....

**Comment by Alex313031** [comment]
@trimechee While Cliqz is no longer around, it was acquired by Ghostery, which makes Ghostery Browser and adblock extension. https://www.ghostery.com/ The npm package is just still named Cliqz-adblock for backwards compatibility, but it is still getting updates and is the best adblocker for Electron https://www.npmjs.com/package/@cliqz/adblocker. Using Ublock origin would require alot of work and needlessly complicate the app, because Electron doesn't have support for Chromium Extensions, which makes you have to use something like https://github.com/ramboxapp/electron-chrome-extensions

**Comment by trimechee** [comment]
Ohh if there is the famous adblock extension of Ghostery, then there is no need for ublock origin! thank you so much for implementing this feature! I close the issue :)
