### ISSUE TITLE
add Star+

### ISSUE THREAD

**Issue by djgerman10** [Alex313031/quark-player#24]
please can add [www.starplus.com](www.starplus.com)
Thank you very much in advance, the application is very good, Saudos from Argentina.

**Comment by Alex313031** [comment]
@djgerman10 You should be able to sign in to disney+ and access most content, since it is a subdivision of disney+ services, or use Ctrl + O to open a custom url (starplus.com in this case).

Star+ is a Latin American only streaming service, not available to the rest of the world, so I won't be adding it to the integrated services list, sorry.

However, last release I did make it where default-services.js is exposed in the application folder, so that a user can edit it.

If you add a line something like:

```
  {
    name: 'Star+',
    title: 'Star+',
    logo: 'starplus.svg',
    url: 'https://www.starplus.com',
    color: '#271F45',
    style: {},
    permissions: []
  },
```

Where starplus.svg is an actual relative path to a logo you want to use, for example https://upload.wikimedia.org/wikipedia/commons/7/71/Star%2B_logo.svg

**Comment by djgerman10** [comment]
> @djgerman10 You should be able to sign in to disney+ and access most content, since it is a subdivision of disney+ services, or use Ctrl + O to open a custom url (starplus.com in this case).
> 
> Star+ is a Latin American only streaming service, not available to the rest of the world, so I won't be adding it to the integrated services list, sorry.
> 
> However, last release I did make it where `default-services.js` is exposed in the application folder, so that a user can edit it.
> 
> Usually found at `C:\Users\$USERNAME\AppData\Local\Programs\quark-player\resources\app.asar.unpacked` where $USERNAME is your actual username, for example mine is "Alex"
> 
> If you add a line something like:
> 
> ```
>   {
>     name: 'Star+',
>     title: 'Star+',
>     logo: 'starplus.svg',
>     url: 'https://www.starplus.com',
>     color: '#271F45',
>     style: {},
>     permissions: []
>   },
> ```
> 
> Where starplus.svg is an actual relative path to a logo you want to use, for example https://upload.wikimedia.org/wikipedia/commons/7/71/Star%2B_logo.svg
> 
> If you need more help, or are using Linux or MacOS instead of Windows, just comment below.

Thank you very much I did it on my personal pc, now I want to put it on linux. How do I do it?

**Comment by Alex313031** [comment]
@djgerman10 On linux, the dir would be

`/opt/Quark Player/resources`

**Comment by YaseenHQ** [comment]
was gonna ask to Implement JioCinema, added it , just unsure how to add the Logo tho
  {
    name: 'JioCinema',
    title: 'JioCinema',
    logo: 'imgs/jc_logo_v2.svg',
    url: 'https://www.jiocinema.com',
    color: '#FF1F7C',
    style: {},
    permissions: []
  },
