### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [Alex313031/quark-player#9]
Does this work with Win 7?

Thanks

**Comment by Alex313031** [comment]
@harryray33 Yes, I still use Windows 7 on some of my machines. That is why I specifically used Electron 22.x.y, because it is the last to support windows 7. Chromium 109 is the last version to support windows 7, and Electron 22 is based on Chromium 108. I also make builds of my browser, Thorium, for Windows 7. I made a nice site with links to that an other useful software, etc. for Windows 7. > https://thorium.rocks/win7
